### ISSUE TITLE
Current RITA to-do-list for 1.3.0

### ISSUE THREAD

**Issue by JShep89** [RitaBot-Project/RitaBot#481]
Requested New Commands

Stage 1:
- [x] !tr settings reset
will reset all settings to the default value. will prompt the user to confirm
- [x] !tr stop for server
will stop all translation task serverwide
- [x] !tr stop for server serverID
will allow us to stop all tasks for a particular server
- [x] add total task count to one of the info readouts
- [x] #504
- [x] #494
- [x] Fix Check command error. Should show !tr help check not !tr check.
- [x] Fix tasks error messages.
- [x] Create !tr tasks server [Server ID] command.
- [x] !tr tasks @userID should also work when taging the users not just manually typing the ID
- [x] tasks command structure should mirror check command structure.
- [x] #503
- [ ] !tr find [server name/owner] (id/username/tag)
- [ ] add target server ID to targeted server stats command
- [ ] Add shard ID to Guild unavailable message. 
- [x] #519
- [x] #536

Stage 2:
- [x] add shard number to stats or check command - added to the check command
- [x] either fix or remove the DDS: to reply function for @user translation functions
- [x] add Server name and ID to the tasks printout for the !tr tasks @userID command
- [x] #502

Stage 3:
- [ ] add a check to prevent auto-detect as a from lang with cross-channel or find a way to allow gifs to be sent to cross-channels when auto is used
- [ ] Fix !tr auto not sending pic and gifs when used for cross-channel or restrict !tr auto to just a same channel command.
- [ ] add same language check to !tr auto command
- [ ] add language check for same channel
- [ ] restrict same lang check to same channel translations
- [ ] create some form of toggle setting for threads(ask @ZyC0R3 ) what he wants it to do
- [ ] #506
- [ ] #505

Stage 4:
- [x] add multilingual bad words filter as a toggleable setting
- [x] add toggle command for profanity filter( 3 value's, "off", "replace" and "delete")

Stage 5:
- [ ] #493
- [ ] #495

Stage 6: 
- [ ] Update all Doc's
- [ ] #496
- [ ] #492
- [ ] Clean up all code
- [ ] Add permission structure as comment to all command files. 

Done:
- [x] fix the UID of the emoji reaction error?
- [x] fix kick command(see comment)
- [x] append Dev name to "Developer identity confirmed"
- [x] add top,gg stat tracker to rita(copy code over from ritabot branch)(SEE COMMENT)
- [x] Fix top.gg code in bot.js, so that if there is no token it ignores the code
- [x] Stop emoji's from translating for auto same channel translations
- [x] strip mentions from same channel translations
- [x] !tr auto to lang for me causes error(see comment)
- [x] update gulpwatch(updated almost all deps except for the ones that broke the test script)

Alt Tasks:
- [ ]  React with ? mark to get source lang
- [ ] #491
- [ ] #490
- [ ] #486
- [ ] #478
- [ ] #510

**Comment by JShep89** [comment]
when using kick command it gives both printouts when only the second should have been given
![image](https://user-images.githubusercontent.com/46389911/145653855-d7b3b012-e092-4f8a-904e-dde27a96229a.png)

**Comment by JShep89** [comment]
> when using kick command it gives both printouts when only the second should have been given ![image](https://user-images.githubusercontent.com/46389911/145653855-d7b3b012-e092-4f8a-904e-dde27a96229a.png)

this issue was already fixed for v1.3.0, implemented the fix fo ritabot branch as well

**Comment by JShep89** [comment]
![image](https://user-images.githubusercontent.com/46389911/145769679-9cef8a68-a2c7-46f2-87e9-2f5d5a4ec8ca.png)
Code works as intended but if there isn't a token in .env or heroku than it fails to build. We need to add in a check to bypass the code if no Token is present.

**Comment by JShep89** [comment]
> ![image](https://user-images.githubusercontent.com/46389911/145769679-9cef8a68-a2c7-46f2-87e9-2f5d5a4ec8ca.png) Code works as intended but if there isn't a token in .env or heroku than it fails to build. We need to add in a check to bypass the code if no Token is present. I don't want to add the code changes to 1.3.0 until a fix for the issue is found.

code is now fixed

**Comment by JShep89** [comment]
> ![image](https://user-images.githubusercontent.com/46389911/146084822-a129786a-2903-4664-b10c-2fa732e150b3.png)

this issue is fixed

**Comment by JShep89** [comment]
module for disableing emoji's:
https://github.com/FrancisLaTruelle/DiscordDisableEmojis/blob/main/discord-disable-emojis.js

**Comment by ZyC0R3** [comment]
#501 needs testing with full fresh build.

**Comment by cyberlooper** [comment]
> #501 needs testing with full fresh build.

This was written in a fresh fork and tested. No other changes were present at the time of its construction.

**Comment by ZyC0R3** [comment]
#504 Will be revisted at later date.
